Do not mount /boot to hardcoded /dev/mmcblk0p1 partition, use fstab entry instead In case of NOOBS environment /dev/mmcblk0p1 is NOOBS and not XBian boot partition, so NOOBS was partly overwritten on firmware updates.

diff --git a/build/rpi/content-tpl/DEBIAN/preinst b/build/rpi/content-tpl/DEBIAN/preinst
--- a/build/rpi/content-tpl/DEBIAN/preinst
+++ b/build/rpi/content-tpl/DEBIAN/preinst
@@ -5,7 +5,7 @@ if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
   exit 0
 fi
 
-{ mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
+mountpoint -q /boot || { mount /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
 
 if [ $1 == "install" -o $1 == "upgrade" ]; then
 
