actual firmware (Sep-10-2013) the shutdown issue is solved, but only with never kernels. tested 3.10.y so ok to install to Beta2 only

diff --git a/content/DEBIAN/preinst b/content/DEBIAN/preinst
--- a/content/DEBIAN/preinst
+++ b/content/DEBIAN/preinst
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-mountpoint -q /boot || mount /boot
+{ mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
 
 if [ $1 == "install" -o $1 == "upgrade" ]; then
 
